services:
  b2s-mock-api:
    image: ghcr.io/hazzemh/back-to-school-mock-api:latest
    container_name: b2s-mock-api
    env_file:
      - .env
    ports:
      - "8001:8000"
    restart: unless-stopped

